### ISSUE TITLE
[Feature Request] options on email subject

### ISSUE THREAD

**Issue by blimeybloke** [yohasebe/fastmail-plus#1]
So I have a request for a feature that I think would help tremendously.  When I am in the inbox, and I mouse over an email, it would be nice if I had some options popup like on gmail to "archive" "trash" mark read" "snooze"

![options](https://user-images.githubusercontent.com/20652035/161624329-ed3813b0-74a3-4221-ad7e-ccc2dcac3f5b.png)

**Comment by yohasebe** [comment]
Thanks for the suggestion! Unfortunately, features other than those already implemented are very difficult to realize since Fastmail does not offer its API, as far as I know. Let's hope Fastmail's original UI gets improved to include features like the one you suggested.

**Comment by blimeybloke** [comment]
ok, thanks, and yes I really hope they do a few tweaks.
