### ISSUE TITLE
CTRL+L shortcut collides with standard browser shortcuts in Win/Linux

### ISSUE THREAD

**Issue by skatkov** [yohasebe/fastmail-plus#5]
A lot of useful features in this browser extension and one of the best one for me is "uncluttered-view mode". 

Unfortunately, it seems that shortcut of it collides with "snap cursor to search bar" shortcut in Win/Linux version of browsers. 
```
    On Windows: Ctrl + L
    On Mac: ⌘ + L
```

In case of Firefox on Windows/Linux, shortcut doesn't even work. 
In case of Chrome it works, but windows looses focus from content and cursor ends up in address/search bar eventually. 

I would propose to change this shortcut " Ctrl + L".  shift +L or alt+L (command+L) maybe? or anything else?

**Comment by yohasebe** [comment]
That sounds reasonable. I have changed the shortcut to `Ctrl + Shift + L`

**Comment by skatkov** [comment]
Great addition, thanks.
